-- Databricks notebook source
-- MAGIC %python
-- MAGIC from pyspark.sql import DataFrame
-- MAGIC import pyspark.sql.functions as F
-- MAGIC
-- MAGIC def agg_by_year(silver_df: DataFrame)-> DataFrame:
-- MAGIC     return silver_df.groupBy(F.col('year')).agg(F.sum('profit').alias('year_wise_profit'))
-- MAGIC
-- MAGIC def agg_by_category(silver_df: DataFrame, silver_df2: DataFrame )-> DataFrame:
-- MAGIC     return silver_df.join(silver_df2, on ='product_id').groupBy(F.col('category')).agg(F.sum('profit').alias('category_wise_profit'))
-- MAGIC
-- MAGIC def agg_by_sub_category(silver_df: DataFrame, silver_df2: DataFrame )-> DataFrame:
-- MAGIC     return silver_df.join(silver_df2, on ='product_id').groupBy(F.col('sub_category')).agg(F.sum('profit').alias('sub_category_wise_profit'))
-- MAGIC
-- MAGIC def agg_by_customer(silver_df: DataFrame, silver_df2: DataFrame )-> DataFrame:
-- MAGIC     return silver_df.join(silver_df2, on ='customer_id').groupBy(F.col('customer_id'), F.col('customer_name')).agg(F.sum('profit').alias('customer_wise_profit'))
